name: Sentinel - Prod

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    container:
      image: julienpeloton/fink-ci:prod
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2

    - name: Download test data
      run: |
        cd $FINK_HOME/datasim
        source $FINK_HOME/datasim/download_ztf_alert_data.sh
        cd $FINK_HOME

    - name: Download simulator
      run: |
        git clone https://github.com/astrolabsoftware/fink-alert-simulator.git

    - name: Set up env
      run: |
        echo "FINK_ALERT_SIMULATOR=${FINK_HOME}/fink-alert-simulator" >> $GITHUB_ENV
        echo "PYTHONPATH=${FINK_HOME}:${FINK_ALERT_SIMULATOR}:${PYTHONPATH}" >> $GITHUB_ENV
        echo "${FINK_HOME}/bin:${FINK_ALERT_SIMULATOR}/bin" >> $GITHUB_PATH

    - name: Check env
      run: |
        echo "FINK_HOME: $FINK_HOME"
        echo "SPARK_HOME: $SPARK_HOME"
        echo "SPARKLIB: $SPARKLIB"
        echo "FINK_ALERT_SIMULATOR: $FINK_ALERT_SIMULATOR"
        echo "KAFKA_HOME: $KAFKA_HOME"
        echo "PYTHONPATH: $PYTHONPATH"
        echo "JAVA_HOME: $JAVA_HOME"
        echo `python -V`

    # - name: Run test suites
    #   run: |
    #     cd $FINK_HOME
    #     fink init -c ${FINK_HOME}/conf/fink.conf.prod
    #     fink_simulator -c ${FINK_HOME}/conf/fink_alert_simulator.conf
    #     fink_test -c conf/fink.conf.prod
    #     curl -s https://codecov.io/bash | bash
    #
    # - uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #   if: always()
